name: app_refeicoes
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  #BD
  sqflite: ^2.2.0+3
  #IMAGE PICKER
  image_picker: ^0.8.6
  #RXDART
  rxdart: ^0.27.7

  #FIREBASE
  firebase_core:
  cloud_firestore: ^4.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  assets:
   - assets/images/
   
  uses-material-design: true

